name: Lint & Format

on:
  pull_request:
  push:
    branches: [main]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Check formatting
        run: dotnet format --verify-no-changes --verbosity diagnostic
